### ISSUE TITLE
Check java crash report "The OTR profile should exist for otr profile id."

### ISSUE THREAD

**Issue by uazo** [bromite/bromite#1012]
### Is the bug a crash?

yes

### Describe the bug

see #1005

```
--------- beginning of crash
03-13 19:06:36.739 31376 31376 E AndroidRuntime: FATAL EXCEPTION: main
03-13 19:06:36.739 31376 31376 E AndroidRuntime: Process: org.bromite.bromite, PID: 31376
03-13 19:06:36.739 31376 31376 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.bromite.bromite/org.chromium.chrome.browser.download.DownloadActivity}: java.lang.IllegalStateException: The OTR profile should exist for otr profile id.
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3780)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3956)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8443)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: Caused by: java.lang.IllegalStateException: The OTR profile should exist for otr profile id.
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at org.chromium.chrome.browser.profiles.OTRProfileID.deserialize(OTRProfileID.java:73)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at org.chromium.chrome.browser.download.DownloadUtils.getOTRProfileIDFromIntent(DownloadUtils.java:184)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at org.chromium.chrome.browser.download.DownloadActivity.onCreate(DownloadActivity.java:70)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8183)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8167)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3753)
03-13 19:06:36.739 31376 31376 E AndroidRuntime: 	... 11 more
03-14 19:16:50.898  8078  8078 E AndroidRuntime: FATAL EXCEPTION: main
03-14 19:16:50.898  8078  8078 E AndroidRuntime: Process: org.bromite.bromite, PID: 8078
03-14 19:16:50.898  8078  8078 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int org.chromium.chrome.browser.tabmodel.TabList.indexOf(org.chromium.chrome.browser.tab.Tab)' on a null object reference
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at org.chromium.chrome.browser.tabmodel.ChromeTabCreator.createNewTab(ChromeTabCreator.java:124)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at org.chromium.chrome.browser.tabmodel.ChromeTabCreator.launchUrl(ChromeTabCreator.java:305)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at org.chromium.chrome.browser.tabmodel.ChromeTabCreator.launchUrl(ChromeTabCreator.java:288)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at org.chromium.chrome.browser.tabmodel.TabCreator.launchNTP(TabCreator.java:95)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at org.chromium.chrome.browser.ChromeTabbedActivity.lambda$initializeToolbarManager$3$ChromeTabbedActivity(ChromeTabbedActivity.java:702)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at org.chromium.chrome.browser.ChromeTabbedActivity$$Lambda$5.onClick(ChromeTabbedActivity.java:2)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at org.chromium.chrome.browser.toolbar.top.TabSwitcherModeTTPhone.onClick(TabSwitcherModeTTPhone.java:92)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at android.view.View.performClick(View.java:8160)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:8137)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at android.view.View.access$3700(View.java:888)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30250)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8443)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
03-14 19:16:50.898  8078  8078 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: FATAL EXCEPTION: main
03-15 07:34:17.121 17084 17084 E AndroidRuntime: Process: org.bromite.bromite, PID: 17084
03-15 07:34:17.121 17084 17084 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int org.chromium.chrome.browser.tabmodel.TabList.indexOf(org.chromium.chrome.browser.tab.Tab)' on a null object reference
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at org.chromium.chrome.browser.tabmodel.ChromeTabCreator.createNewTab(ChromeTabCreator.java:124)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at org.chromium.chrome.browser.tabmodel.ChromeTabCreator.launchUrl(ChromeTabCreator.java:305)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at org.chromium.chrome.browser.tabmodel.ChromeTabCreator.launchUrl(ChromeTabCreator.java:288)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at org.chromium.chrome.browser.tabmodel.TabCreator.launchNTP(TabCreator.java:95)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at org.chromium.chrome.browser.ChromeTabbedActivity.lambda$initializeToolbarManager$3$ChromeTabbedActivity(ChromeTabbedActivity.java:702)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at org.chromium.chrome.browser.ChromeTabbedActivity$$Lambda$5.onClick(ChromeTabbedActivity.java:2)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at org.chromium.chrome.browser.toolbar.top.TabSwitcherModeTTPhone.onClick(TabSwitcherModeTTPhone.java:92)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at android.view.View.performClick(View.java:8160)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:8137)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at android.view.View.access$3700(View.java:888)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30250)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8443)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
03-15 07:34:17.121 17084 17084 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

as I think it is not related to the above issue, I open another task to report it

**Comment by uazo** [comment]
it's a upstream bug, resolved with

https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/profiles/android/java/src/org/chromium/chrome/browser/profiles/OTRProfileID.java;l=58;drc=ace0dbba34cb64df4c03c7d09e734f6f6a9669d6;bpv=1;bpt=0;dlc=b7471fc44d223d82613605c30bcc5129f2b27082

```
// The off-the-record profile should exist for the given OTRProfileID, since OTRProfileID
// creation is completed just before the profile creation. So there should always be a
// profile for the id. If OTR profile is not available, deserialize function should not be
// called.
```

**Comment by csagan5** [comment]
In which version has this been fixed?

**Comment by uazo** [comment]
I don't know, I still haven't figured out how to track the version from a commit. can you explain it to me?

**Comment by csagan5** [comment]
You can go here: `https://github.com/chromium/chromium/tree/<commit hash>` and then check which tags have the commit

**Comment by csagan5** [comment]
The commit should be this one: https://github.com/chromium/chromium/commit/b7471fc44d223d82613605c30bcc5129f2b27082

So it looks like it was not backported to v89

**Comment by uazo** [comment]
> So it looks like it was not backported to v89

https://github.com/chromium/chromium/commit/af77de2f016ab2c8057a5dccdfd717309eb79d7b
now it seems so. I close this point because upstream resolved it
