### ISSUE TITLE
Crash when opening the app

### ISSUE THREAD

**Issue by Primokorn** [bromite/bromite#121]
**Version**

Version: `v69.0.3497.73.`
Arch: `arm64_ChromeModernPublic.apk`

**Is the bug reproducible with latest version?**
`Oui and it started with the latest version`

**Can the bug be reproduced with corresponding [Chromium](https://github.com/bromite/chromium/releases) version?**
`No`

**Is the bug a crash?**
Yes

**Describe the bug**
Open the app.
I tried to uninstall then reinstall the app. I use Bromite webview (latest version too).

[logcat_09-05-2018_09-28-55.txt](https://github.com/bromite/bromite/files/2351825/logcat_09-05-2018_09-28-55.txt)

**Comment by csagan5** [comment]
From your log, the crash seems to be:
```
libraryName: /data/app/org.bromite.bromite-paukMSw5fmpq-cJxyh2zxg==/base.apk!/lib/arm64-v8a/crazy.libchrome.so
Shutting down VM
FATAL EXCEPTION: main
Process: org.bromite.bromite, PID: 14251
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.bromite.bromite/org.chromium.chrome.browser.ChromeTabbedActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2779)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2857)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6499)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at oo.r(PG:3354)
	at oo.b(PG:284)
	at nY.setContentView(PG:139)
	at Sh.m(PG:472)
	at Sh.l(PG:455)
	at arh.a(PG:151)
	at art.a(PG:173)
	at arh.onCreate(PG:7311)
	at android.app.Activity.performCreate(Activity.java:7009)
	at android.app.Activity.performCreate(Activity.java:7000)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2732)
	... 10 more
  Force finishing activity org.bromite.bromite/com.google.android.apps.chrome.Main
Showing crash dialog for package org.bromite.bromite u0
```

Since it does not happen for all users, is this something related to themes? Have you tried with Chrome v69 and theming enabled for that?

**Comment by Primokorn** [comment]
I thought Substratum are disabled if they generate several FCs in a row. I was wrong.
