### ISSUE TITLE
Websocket connection fails

### ISSUE THREAD

**Issue by alexgleason** [bromite/bromite#1294]
### Bromite version

Version: 91.0.0.1
Arch: arm64
Android version: 11
Device model: Pocophone F1

### Flags

These are the flags changed under `chrome://flags`:

Default

### Is this bug about the SystemWebView?

I don't know

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

No

### Is this bug happening in an incognito tab?
No

### Allow ads for the site; is the bug caused by the adblocker?
No

### Is the bug a crash?

No

### Steps to reproduce the bug

1. Sign into gleasonator.com
2. Do something else for a while
3. Load the page again
4. It throws an error.

### Expected behavior

The websocket connection works.

### Screenshots

![Screenshot from 2021-07-22 19-25-24](https://user-images.githubusercontent.com/3639540/126725633-da5fa830-2d5c-49ff-a992-44dba0c224da.png)

```
react-dom.production.min.js:5108
DOMException: Failed to construct 'WebSocket': Access to this address is not allowed.
    at WebSocketClient.value (https://gleasonator.com/packs/js/application-f9face3b504e0c4034c8.chunk.js:2:1864977)
    at new WebSocketClient (https://gleasonator.com/packs/js/application-f9face3b504e0c4034c8.chunk.js:2:1864799)
    at getStream (https://gleasonator.com/packs/js/application-f9face3b504e0c4034c8.chunk.js:2:570260)
    at https://gleasonator.com/packs/js/application-f9face3b504e0c4034c8.chunk.js:2:569594
    at https://gleasonator.com/packs/js/application-f9face3b504e0c4034c8.chunk.js:2:2480651
    at UI.connectStreaming (https://gleasonator.com/packs/js/application-f9face3b504e0c4034c8.chunk.js:2:2861183)
    at UI.value (https://gleasonator.com/packs/js/application-f9face3b504e0c4034c8.chunk.js:2:2866402)
    at Ji (https://gleasonator.com/packs/js/application-f9face3b504e0c4034c8.chunk.js:2:2148067)
    at Sj (https://gleasonator.com/packs/js/application-f9face3b504e0c4034c8.chunk.js:2:2165614)
    at https://gleasonator.com/packs/js/application-f9face3b504e0c4034c8.chunk.js:2:2185635
```

This is my own social media software that I develop, so if there's code I can change to make it work in Bromite I would like to. Upstream issue: https://gitlab.com/soapbox-pub/soapbox-fe/-/issues/704

The code that fails is here: https://gitlab.com/soapbox-pub/soapbox-fe/-/blob/develop/app/soapbox/stream.js#L77

This script is served by a ServiceWorker:

![Screenshot from 2021-07-22 19-47-09](https://user-images.githubusercontent.com/3639540/126725903-fd157647-370a-4a9a-98fb-f19e58102551.png)

A user of my software raised this issue after I enabled the ServiceWorker. The fact it only happens after reloading the page makes me think maybe Bromite considers the Service Worker to be a "mismatched" origin.

The domain is `https://gleasonator.com` and the websocket is `wss://gleasonator.com`, so there is no mismatch.

**Comment by kokukyocho** [comment]
Hello @alexgleason!

I am a bot :robot:

Thanks for submitting this issue!
I noticed that it is missing the template, please edit the issue to match the template for either a [bug](https://github.com/bromite/bromite/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) or a [feature request](https://github.com/bromite/bromite/blob/master/.github/ISSUE_TEMPLATE/feature_request.md).

The issue will be automatically re-opened after that.

**Tip**: if you use GitHub in Desktop mode the template will be proposed to you when submitting issues.

**Comment by alexgleason** [comment]
I followed the issue template but it closed this anyway.

**Comment by alexgleason** [comment]
I disabled the Service Worker completely and the problem no longer happens. It wasn't enough to stop serving the .js scripts from the Service Worker, I had to disable it entirely.

**Comment by alexgleason** [comment]
It seems that serving the js scripts from the Service Worker is okay, but serving the site index (`/`) is not. I don't want to be doing that anyway (it was by accident) and after removing it the site works again without any compromises.

This is probably still a bug, but at least now there's a workaround.

This is my fix: https://gitlab.com/soapbox-pub/soapbox-fe/-/merge_requests/638/diffs

**Comment by alexgleason** [comment]
I've updated to `93.0.4577.110` and the issue still occurs. I have read the other issues but I think they didn't pinpoint exactly where the problem is:

If a ServiceWorker serves the index.html file from its cache (as in a SPA), and that index file contains `<script src="...">` pointing to a javascript file which calls `new WebSocket()`, the code crashes with a SecurityError.

The host is `https://gleasonator.com` and the WebSocket is `wss://gleasonator.com`. There is no mismatched origin. I think Bromite is confused by the index.html being served from a ServiceWorker. I think it believes the ServiceWorker cache is a different origin than the WebSocket URI.
