### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by shuvashish76** [bromite/bromite#1375]
### Bromite version

Version: `92.0.4515.176 (1630365560)`
Arch: `arm64`
Android version: `8.1.0`
Device model: `Lenovo Tab4 8 plus (TB-8704X)`
RAM: `3GB`

### Is the bug reproducible with latest version?

Yes

### Is this bug happening in an incognito tab?

Yes

### Allow ads for the site; is the bug caused by the adblocker?

Not sure. Probably not.

### Is the bug a crash?

Yes

Yes, this is the crash dump:
```
FATAL EXCEPTION: main
Process: org.bromite.bromite, PID: 24745
java.lang.RuntimeException: Unable to resume activity {org.bromite.bromite/com.google.android.apps.chrome.Main}: java.lang.IllegalArgumentException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3584)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3624)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1641)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalArgumentException
	at android.os.Parcel.readException(Parcel.java:2017)
	at android.os.Parcel.readException(Parcel.java:1959)
	at android.app.IActivityManager$Stub$Proxy.isTopOfTask(IActivityManager.java:8364)
	at android.app.Activity.isTopOfTask(Activity.java:6315)
	at android.app.Activity.onResume(Activity.java:1314)
	at X20.onResume(chromium-ChromePublic.apk-stable-1630365560:1)
	at vd.onResume(chromium-ChromePublic.apk-stable-1630365560:1)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)
	at android.app.Activity.performResume(Activity.java:7131)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3559)
	... 8 more
```

### Describe the bug

I was watching some youtube videos then went back to home screen. Bromite stopped & crashed after few seconds...

**Comment by kokukyocho** [comment]
Hello @shuvashish76!

I am a bot :robot:

Thanks for submitting this issue!
I noticed that it is missing the template, please edit the issue to match the template for either a [bug](https://github.com/bromite/bromite/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) or a [feature request](https://github.com/bromite/bromite/blob/master/.github/ISSUE_TEMPLATE/feature_request.md); the issue will be automatically re-opened afterwards.

If this is not an issue nor a feature request and you want to start a discussion then you can use [GitHub Discussions](https://github.com/bromite/bromite/discussions).

**Tip**: if you use GitHub in Desktop mode the template will be proposed to you when submitting issues.
