### ISSUE TITLE
Aw, Snap! On password autofill

### ISSUE THREAD

**Issue by pilsnerbeer** [bromite/bromite#1570]
### Bromite version

Version: 95.0.4638.78
Arch: arm64
Android version: 10
Device model: op5T

### Flags

These are the flags changed under `chrome://flags`:

### Is this bug about the SystemWebView?

?

### Is the bug reproducible with latest version?

yes
### Can the bug be reproduced with corresponding Chromium version?
no

### Is this bug happening in an incognito tab?
yes

### Allow ads for the site; is the bug caused by the adblocker?
no

### Is the bug a crash?

yes (aw, snap! something went wrong)

-- or --

Yes, this is the crash dump:
```
<paste here logcat dump individuated with 'adb logcat | grep chromium'>
```

### Describe the bug

if you have a password saved for a website, click the password field and then the corresponding login details in a popup, the website then freezes and crashes. this never happened before and I believe it was directly caused by the latest update released few days ago

### Steps to reproduce the bug

Steps to reproduce the bug:
1. have a password saved for website (affected https://www.vut.cz/en/login)
2. click password field, tap your login details
3. website crashes
Do not write "any website", specify which URLs can be used to reproduce the issue.

### Expected behavior

password details fill in with no crashes (works on github.com)

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/36133540/141615544-8e238953-7712-4cf1-86e6-2aff56506dd1.png)

**Comment by uazo** [comment]
can you add the crash report dump? you can download it from `chrome://crashes`

**Comment by elcste** [comment]
I am seeing this issue as well.

@uazo Here's my crash dump:

[3bcdbfeb-0ebb-4fc9-af91-5eaaf8eaa6f7.zip](https://github.com/bromite/bromite/files/7549340/3bcdbfeb-0ebb-4fc9-af91-5eaaf8eaa6f7.zip)

**Comment by uazo** [comment]
this is what is recoverable, the obfuscation of the PII is invasive but it is understood anyway.
thank you @elcste 

```
java.lang.Exception: Stack trace
     at java.lang.Thread.dumpStack(HTTP://WEBADDRESS.ELIDED)
     at org.chromium.components.browser_ui.bottomsheet.BottomSheet.showContent(BottomSheet.java:515)
     at Xq.r(HTTP://WEBADDRESS.ELIDED-stable-1636070480:5)
     at Wq.i(HTTP://WEBADDRESS.ELIDED-stable-1636070480:13)
     at org.chromium.components.browser_ui.bottomsheet.BottomSheet.setInternalCurrentState(BottomSheet.java:1015)
     at Lq.onAnimationEnd(HTTP://WEBADDRESS.ELIDED-stable-1636070480:9)
     at android.animation.Animator$HTTP://WEBADDRESS.ELIDED(HTTP://WEBADDRESS.ELIDED)
     at android.animation.ValueAnimator.endAnimation(HTTP://WEBADDRESS.ELIDED)
     at android.animation.ValueAnimator.doAnimationFrame(HTTP://WEBADDRESS.ELIDED)
     at android.animation.AnimationHandler.doAnimationFrame(HTTP://WEBADDRESS.ELIDED)
     at android.animation.AnimationHandler.access$100(HTTP://WEBADDRESS.ELIDED)
     at android.animation.AnimationHandler$HTTP://WEBADDRESS.ELIDED(HTTP://WEBADDRESS.ELIDED)
     at android.view.Choreographer$HTTP://WEBADDRESS.ELIDED(HTTP://WEBADDRESS.ELIDED)
     at android.view.Choreographer.doCallbacks(HTTP://WEBADDRESS.ELIDED)
     at android.view.Choreographer.doFrame(HTTP://WEBADDRESS.ELIDED)
     at android.view.Choreographer$HTTP://WEBADDRESS.ELIDED(HTTP://WEBADDRESS.ELIDED)
     at android.os.Handler.handleCallback(HTTP://WEBADDRESS.ELIDED)
     at android.os.Handler.dispatchMessage(HTTP://WEBADDRESS.ELIDED)
     at android.os.Looper.loop(HTTP://WEBADDRESS.ELIDED)
     at android.app.ActivityThread.main(HTTP://WEBADDRESS.ELIDED)
     at java.lang.reflect.Method.invoke(Method.java)
     at com.android.internal.os.RuntimeInit$HTTP://WEBADDRESS.ELIDED(HTTP://WEBADDRESS.ELIDED)
     at com.android.internal.os.ZygoteInit.main(HTTP://WEBADDRESS.ELIDED)

```

**Comment by uazo** [comment]
and this is the native dump

```
Crash reason:  SIGTRAP
Crash address: 0x7ec06354
Process uptime: 77 seconds

Thread 15 (crashed)
 0  libchrome.so!base::WeakPtr<net::DnsSession>::operator->() const [weak_ptr.h : 252 + 0x0]
    Found by: given as instruction pointer in context

    Possible instruction pointers:
 1  libchrome.so!autofill::PasswordAutofillAgent::TrackAutofilledElement(blink::WebFormControlElement const&) [password_autofill_agent.cc : 730 + 0x7]
    Found by: call frame info

    Possible instruction pointers:
     *(0x83dfe00c) = 0x81fcbba3 <autofill::PasswordAutofillAgent::FillField(blink::WebInputElement*, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&)> [password_autofill_agent.cc : 0 + 0x1]

 2  libchrome.so!autofill::PasswordAutofillAgent::FillField(blink::WebInputElement*, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&) [password_autofill_agent.cc : 803 + 0x7]
    Possible instruction pointers:
     *(0x83dfe034) = 0x81fcbbcf <autofill::PasswordAutofillAgent::FillPasswordFieldAndSave(blink::WebInputElement*, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&)> [password_autofill_agent.cc : 0 + 0x1]

 3  libchrome.so!autofill::PasswordAutofillAgent::FillPasswordFieldAndSave(blink::WebInputElement*, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&) [password_autofill_agent.cc : 811 + 0x5]
    Possible instruction pointers:
     *(0x83dfe054) = 0x81fcb7b5 <autofill::PasswordAutofillAgent::FillSuggestion(blink::WebFormControlElement const&, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&)> [password_autofill_agent.cc : 0 + 0x1]

 4  libchrome.so!autofill::PasswordAutofillAgent::FillSuggestion(blink::WebFormControlElement const&, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&, std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const&) [password_autofill_agent.cc : 772 + 0x7]
    Possible instruction pointers:
     *(0x83dfe078) = 0x8215e2fc <__ThumbV7PILongThunk__ZN4absl13base_internalL18LLA_SkiplistDeleteEPNS0_12_GLOBAL__N_19AllocListES3_PS3_> [ : 0 + 0x8215e2fc]
     *(0x83dfe080) = 0x8215e2fc <__ThumbV7PILongThunk__ZN4absl13base_internalL18LLA_SkiplistDeleteEPNS0_12_GLOBAL__N_19AllocListES3_PS3_> [ : 0 + 0x8215e2fc]
     *(0x83dfe0ac) = 0x7f763503 <autofill::mojom::AutofillAgentStubDispatch::Accept(autofill::mojom::AutofillAgent*, mojo::Message*)> [autofill_agent.mojom.cc : 0 + 0x9]

 5  libchrome.so!autofill::mojom::AutofillAgentStubDispatch::Accept(autofill::mojom::AutofillAgent*, mojo::Message*) [autofill_agent.mojom.cc : 0 + 0x7]
 
    Possible instruction pointers:
     *(0x83dfe0bc) = 0x8006896b <base::sequence_manager::internal::WorkQueue::RemoveAllCanceledTasksFromFront()> [vector : 665 + 0x1]
     *(0x83dfe0d8) = 0x80000010 <ChromeSigninStatusMetricsProviderDelegate::GetStatusOfAllAccounts()> [vector : 659 + 0x4]
     *(0x83dfe0dc) = 0x81344f2d <blink::WorldSafeV8Reference<v8::Value>::WorldSafeV8Reference(blink::WorldSafeV8Reference<v8::Value> const&)> [scoped_refptr.h : 197 + 0x1]
     *(0x83dfe0f4) = 0x81ab2c5f <v8::Maybe<blink::ScriptValue> blink::bindings::CallbackInvokeHelper<blink::CallbackFunctionBase, (blink::bindings::CallbackInvokeHelperMode)0>::Result<blink::IDLAny, blink::ScriptValue>()> [callback_invoke_helper.h : 0 + 0x1]
     *(0x83dfe108) = 0x820d9a80 <__ThumbV7PILongThunk__ZN4absl13base_internalL18LLA_SkiplistDeleteEPNS0_12_GLOBAL__N_19AllocListES3_PS3_> [ : 0 + 0x820d9a80]
     *(0x83dfe13c) = 0x81ab1fff <blink::bindings::CallbackInvokeHelper<blink::CallbackFunctionBase, (blink::bindings::CallbackInvokeHelperMode)0>::~CallbackInvokeHelper()> [callback_invoke_helper.h : 100 + 0x1]
     *(0x83dfe144) = 0x81ab3823 <blink::V8Function::Invoke(blink::bindings::V8ValueOrScriptWrappableAdapter, blink::HeapVector<blink::ScriptValue, 0u> const&)> [v8_function.cc : 0 + 0x1]
     *(0x83dfe1c0) = 0x7fffffff <ChromeSigninStatusMetricsProviderDelegate::GetStatusOfAllAccounts()> [chrome_signin_status_metrics_provider_delegate.cc : 54 + 0x1]
     *(0x83dfe1dc) = 0x7eb60df4 <__gnu_uldivmod_helper> [bpabi.c : 54 + 0x0]
     *(0x83dfe1f4) = 0x7eb610cc <__aeabi_uldivmod> [ : 0 + 0x7eb610cc]
     *(0x83dfe1fc) = 0x7ec02349 <bool base::internal::CheckedMulImpl<long long>(long long, long long, long long*)> [checked_math_impl.h : 167 + 0x1]
     *(0x83dfe210) = 0x7fffffff <ChromeSigninStatusMetricsProviderDelegate::GetStatusOfAllAccounts()> [chrome_signin_status_metrics_provider_delegate.cc : 54 + 0x1]
     *(0x83dfe244) = 0x7eb88974 <__fixunsdfdi> [libgcc2.c : 1414 + 0x24]
     *(0x83dfe284) = 0x7ebfba0d <bool mojo::internal::ValidateContainer<mojo::internal::Array_Data<unsigned short> >(mojo::internal::Pointer<mojo::internal::Array_Data<unsigned short> > const&, mojo::internal::ValidationContext*, mojo::internal::ContainerValidateParams const*)> [validation_util.h : 0 + 0x1]
     *(0x83dfe294) = 0x7ebfb9c5 <mojo_base::mojom::internal::String16_Data::Validate(void const*, mojo::internal::ValidationContext*)> [string16.mojom-shared.cc : 0 + 0x1]
     *(0x83dfe2c0) = 0x82160748 <__ThumbV7PILongThunk__ZN4absl13base_internalL18LLA_SkiplistDeleteEPNS0_12_GLOBAL__N_19AllocListES3_PS3_> [ : 0 + 0x82160748]
     *(0x83dfe2c4) = 0x822f3e30 <__ThumbV7PILongThunk__ZN4absl13base_internalL18LLA_SkiplistDeleteEPNS0_12_GLOBAL__N_19AllocListES3_PS3_> [ : 0 + 0x822f3e30]
     *(0x83dfe2d4) = 0x80222db3 <mojo::InterfaceEndpointClient::HandleIncomingMessageThunk::Accept(mojo::Message*)> [interface_endpoint_client.cc : 0 + 0x1]

```

**Comment by uazo** [comment]
I think it may be an upstream bug, at this function:
```
void PasswordAutofillAgent::TrackAutofilledElement(
    const blink::WebFormControlElement& element) {
  autofill_agent_->TrackAutofilledElement(element);
}
```
for `autofill_agent_`, in the same class, the existence is always verified like this
```
  AutofillAgent* agent = autofill_agent_.get();
  if (agent) {
    .....
  }
```
except at that point.
unfortunately, without the possibility of verifying it directly, I could not do better.
if maybe the reporters can give me some suggestions on how to replicate the crash, in the meantime I will prepare a pull with this change and with the flag to disable autofill in incognito mode.

**Comment by csagan5** [comment]
> unfortunately, without the possibility of verifying it directly, I could not do better.

Is there a Chromium bug open for this?

**Comment by uazo** [comment]
for the java stack dump there is [1126872](https://bugs.chromium.org/p/chromium/issues/detail?id=1126872), but it is blocked, anyway, I don't think it has anything to do with our crash.
for the native part, the method refers to [1140497](https://bugs.chromium.org/p/chromium/issues/detail?id=1140497), but nothing interesting.

if I search for [autofill crash](https://bugs.chromium.org/p/chromium/issues/list?q=autofill%20crash&can=2), I find something, but without access to their crash reports I cannot know if they are related to our problem.

**Comment by csagan5** [comment]
@pilsnerbeer please attach the crash dump as explained in template instructions and then we can re-open this.

**Comment by pilsnerbeer** [comment]
I have obtained the crash dump. I cant read its contents fully, so is it safe to paste it here publicly regarding possible sensitive info (passwords?)?

**Comment by elcste** [comment]
FWIW, with the latest release v96.0.4664.54, this isn't occurring for me on the one site I was seeing it on.

**Comment by csagan5** [comment]
> I have obtained the crash dump. I cant read its contents fully, so is it safe to paste it here publicly regarding possible sensitive info (passwords?)?

Passwords are not included; you can check yourself before posting the file, use a hex editor since opening the MIME files is more difficult.
