### ISSUE TITLE
Cannot install any UserScripts. "Add script" results in crash. Opening from Downloads results in the error "Cannot open script source"

### ISSUE THREAD

**Issue by firepacket** [bromite/bromite#1926]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

99.0.4844.58

### Device architecture

arm64-v8a

### Android version

10

### Device model

Oneplus 7 Pro

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

Yes

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

2. Yes, I have attached the crash report dump that I downloaded from chrome://crashes

[5bd8ac2a-ac18-46a8-8157-8cad5466bca5.zip](https://github.com/bromite/bromite/files/8356161/5bd8ac2a-ac18-46a8-8157-8cad5466bca5.zip)

### Describe the bug

1. When I try to add a userscript by going into "Settings -> Userscripts -> Add script" the application crashes and I have attached the log of this crash.

2. When I try to add a userscript by opening a user.js file from Downloads I get the error in a toast: "Cannot open script source" but the application does not crash.

### Steps to reproduce the bug

I simply downloaded and installed the Bromite apk from this website and attempted to install ANY userscript by both methods I described above which resulted in either a crash or an error toast message.

### Expected behavior

I should be able to install new user.js userscripts by using the "Add script" button or executing it from the Downloads page.

### Screenshots

Trying to Install script from Downloads:

![Open from Downloads](https://user-images.githubusercontent.com/3860274/160254494-f102b1eb-6065-4f45-ac33-3d01f79d3ec9.jpg)

![Open from Downloads toast ERROR](https://user-images.githubusercontent.com/3860274/160254539-33174385-666b-4b6e-a777-f4927607cd0a.jpg)

Trying to Install script with 'Add Script':

![Screenshot-crash](https://user-images.githubusercontent.com/3860274/160254570-d82e7749-8ae4-48e8-b160-788feb331925.jpg)

**Comment by kokukyocho** [comment]
Hello @firepacket!

I am a bot :robot:

Thanks for submitting this issue!
I noticed that it is missing the template, please edit the issue to match the template for either a [bug](https://github.com/bromite/bromite/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml) or a [feature request](https://github.com/bromite/bromite/blob/master/.github/ISSUE_TEMPLATE/feature_request.yml); the issue will be automatically re-opened afterwards.

If this is not an issue nor a feature request and you want to start a discussion then you can use [GitHub Discussions](https://github.com/bromite/bromite/discussions).

**Tip**: if you use GitHub in Desktop mode the template will be proposed to you when submitting issues.

**Comment by csagan5** [comment]
@firepacket this crash dump is not generated with the latest version of Bromite, please use the latest version.

The crash seems due to Bromite not having yet saved any file; @uazo assuming that the issue is such, any idea how to prevent it?

**Comment by uazo** [comment]
> The crash seems due to Bromite not having yet saved any file
> any idea how to prevent it?

@firepacket try using another folder for the file.
that log does not refer to that error, but, if after trying again, you try to generate a new one ("Generate report" in `chrome://crashes`) we can maybe check.
you can also activate `chrome://flags/#enable-userscripts-log`, so we can have more details

**Comment by firepacket** [comment]
@uazo @csagan5 I submitted a new crash log in my other bug report that addressed these issues. It is from the newest version and definitely from the userscript install crash. I don't understand why this bot is saying the report does not match the template when it does.

The reason "Add script" is crashing is probably because I have a rooted phone and have disabled the Download manager. If you weren't aware, that thing allows any app on the phone to access the internet at any time which bypasses firewall rules. That is likely the cause of the crash from clicking "Add script"., but doesn't explain not being able to read the script from the Bromite Download page.

I don't think it's right to require that browser software depend on a poorly designed, anti-security, and anti-privacy download manager. What other browser needs a download manager? The browser can download files just fine without it, so what is the purpose of the dependency?

Simply because you guys cannot reproduce it by not enforcing basic device security policies on your device, does not mean this is not a real bug. The browser should not require a superfluous leaky, external application to download and install scripts. There are plenty of people who know the Download manager is a massive security hole and have it disabled. This is still a valid bug for all other security conscious phone users.

Even ignoring the Download manager, the install of userscripts should be possible by opening a downloaded user.js file from the Bromite Downloads page. This shouldn't need the Download manager. I have tried downloading to different locations with the same results: "Cannot open script source"

I have enabled the userscripts log but I have no idea where the log is being saved. Opening the file from Downloads does not crash, it only errors, and I can open my all other downloads from that screen without issue.

If someone would please give me any further information on how this could be resolved, it would be most appreciated.

I am saddened to see that nobody appears to take this issue seriously even after resubmitting the bug. :-(

**Comment by csagan5** [comment]
> I don't understand why this bot is saying the report does not match the template when it does.

This issue here #1926 was closed because the bot saw that you were not using the latest version (`99.0.4844.58` while latest is `99.0.4844.77` at time of writing), issue #1928 was closed by me because we had already started discussing it here and instead of opening a new one you should have edited this one as mentioned [here](https://github.com/bromite/bromite/issues/1926#issuecomment-1079787046). The crash dump in #1928 is usable (since generated with the correct version of Bromite) but discussion was already happening here so now we have to deal with broken context for the discussion.

@uazo commented [here](https://github.com/bromite/bromite/issues/1926#issuecomment-1080613626) that the crash dump in this issue #1926 is not valid.

This is what the crash dump in this issue #1926 contains:
```
E chromium: [ERROR:directory_reader_posix.cc(42)] opendir /data/user/0/HTTP://WEBADDRESS.ELIDED: No such file or directory (2)
[...]
android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:905)
        at android.content.res.Resources.getDrawable(Resources.java:845)
        at org.chromium.base.e.h(chromium-ChromePublic.apk-stable-1646292930:2)
        at org.chromium.chrome.browser.toolbar.menu_button.MenuButton.a(chromium-ChromePublic.apk-stable-1646292930:21)
        at oz0.b(chromium-ChromePublic.apk-stable-1646292930:31)
        at oz0.f(Unknown Source:6)
        at R11.i(Unknown Source:8)
        at V11.c(chromium-ChromePublic.apk-stable-1646292930:2)
        at O11.p(chromium-ChromePublic.apk-stable-1646292930:8)
        at jz0.b(chromium-ChromePublic.apk-stable-1646292930:4)
        at bz0.run(chromium-ChromePublic.apk-stable-1646292930:3)
        at ON1.onResult(chromium-ChromePublic.apk-stable-1646292930:3)
        at WN1.c(Unknown Source:23)
        at WN1.a(chromium-ChromePublic.apk-stable-1646292930:27)
        at SN1.run(Unknown Source:2)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

This is what the crash dump in #1928 contains:
```
E chromium: [ERROR:user_script_loader.cc(661)] UserScriptLoader: load error Cannot open script source.
[...]
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=HTTP://WEBADDRESS.ELIDED.OPEN_DOCUMENT cat=[HTTP://WEBADDRESS.ELIDED] typ=*/* flg=0x1 }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2241)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1895)
        at android.app.Activity.startActivityForResult(Activity.java:5205)
        at kF.startActivityForResult(chromium-ChromePublic.apk-stable-1647398380:2)
        at b3.a(chromium-ChromePublic.apk-stable-1647398380:37)
        at androidx.fragment.app.c.B0(chromium-ChromePublic.apk-stable-1647398380:6)
        at Y80.b(Unknown Source:3)
        at Ai0.b(chromium-ChromePublic.apk-stable-1647398380:3)
        at org.chromium.ui.base.WindowAndroid.w(chromium-ChromePublic.apk-stable-1647398380:3)
        at Ga1.onClick(chromium-ChromePublic.apk-stable-1647398380:8)
        at android.view.View.performClick(View.java:7201)
        at android.view.View.performClickInternal(View.java:7170)
        at android.view.View.access$3500(View.java:806)
        at android.view.View$PerformClick.run(View.java:27562)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

I have no idea whether the activity error is related or not; @uazo is this crash also invalid? Perhaps the error "Cannot open script source." could tell a bit more about the reason?

> The reason "Add script" is crashing is probably because I have a rooted phone and have disabled the Download manager.

How do you conclude that? The crash dump allows to pinpoint (in most cases, provided that it is the actual crash at hand) the reason for the crash.

> I don't think it's right to require that browser software depend on a poorly designed, anti-security, and anti-privacy download manager. What other browser needs a download manager? The browser can download files just fine without it, so what is the purpose of the dependency?

Does Bromite depend on the Android download manager? Are you referring to [SAF](https://developer.android.com/training/data-storage/shared/documents-files)? @uazo does SAF correspond to a dependency on the Android download manager?

> Simply because you guys cannot reproduce it by not enforcing basic device security policies on your device, does not mean this is not a real bug.

Nobody is saying that it is not a real bug, but either we can reproduce it or we have a crash dump to inspect; any other bug, real or not, cannot be investigated/fixed and nobody can do absolutely anything about it.

> Even ignoring the Download manager, the install of userscripts should be possible by opening a downloaded user.js file from the Bromite Downloads page.

What you call "Bromite Downloads page" is rather the internal app data stored in the internal storage (in most cases).
Again you are assuming that someone wants to ignore the Download manager; nobody wants to ignore anything: the answer is in the crash dump and that's where it can be found.

> I have enabled the userscripts log but I have no idea where the log is being saved. Opening the file from Downloads does not crash, it only errors, and I can open my all other downloads from that screen without issue.
> 
> If someone would please give me any further information on how this could be resolved, it would be most appreciated.

I have added an explanation for the flag here: https://github.com/bromite/bromite/wiki/UserScripts#flags
UserScripts is still considered an experimental feature, see https://github.com/bromite/bromite/issues/792

In order to continue troubleshooting please follow what @uazo asked [here](https://github.com/bromite/bromite/issues/1926#issuecomment-1080613626):
* try using another folder for the file; if you get again the crash, click on "Generate report" in `chrome://crashes` and attach here the new report
* when you do this test please extract the extended UserScripts logging information as explained in the wiki page (`adb logcat | grep UserScripts`) and submit it here in a comment or as a text file; you can remove the URLs or script names for privacy reasons

> I am saddened to see that nobody appears to take this issue seriously even after resubmitting the bug. :-(

Please stop assuming anything: that you have found the reason for the crash, that the bug is considered not real, that the issue is not taken seriously. I have asked you in #1928 to follow @uazo's instructions and once you would do that the issue would be re-opened because there would be information to investigate it. Without such information the issue stays closed; if you have troubles following @uazo's instructions, which is perfectly understandable, just ask for better explanations: it would need a shorter and more neutral comment write-up from you and it would be replied promptly with any information you need.

**Comment by csagan5** [comment]
> Please forgive me, but I hope you can understand how the swift closing of both my first and second bug report does indeed send a loud public message that this issue is not important. You say you closed my second bug report because I already opened one, but yet that one was deemed invalid and closed? Why close it if you expect me to fix it? Am I supposed to assume that it is common practice to actively troubleshoot _closed_ bug reports? Since there was no information in [#1926](https://github.com/bromite/bromite/issues/1926) that was not also reproduced in in [#1928](https://github.com/bromite/bromite/issues/1928), the action of closing that bug report doesn't appear to serve any helpful purpose.

Again, you are not supposed to suppose anything: read comments, do what is asked if you want to contribute, otherwise don't do it but don't complain that things are not as you expect. You were told in #1928 what to do, you could/would not do it and you did not ask for help but instead complained, and you still are. This is toxic behaviour so please stop.



> > Nobody is saying that it is not a real bug, but either we can reproduce it or we have a crash dump to inspect; any other bug, real or not, cannot be investigated/fixed and nobody can do absolutely anything about it.
> 
> So you are saying that you are completely unable to fix bugs that throw error messages describing broken functionality? You can't fix anything that doesn't result in a crash? You don't even want to open a dialog to find out if you actually can fix it or not?

No, I am not. This is a crash and it can only be fixed by using crash reports. If it were not a crash, nobody would ask you about a crash report.

> You have admitted that second bug report did indeed contain a valid crash log, yet there still was no discussion or troubleshooting aside from closing the issue. You have only now posted more details regarding the problem that allows me to discuss it with you further and troubleshoot, but the curt response to both my bug reports was highly discouraging.

That is because that report was created **before** the tests that were asked of you, not after. Given the new tests/crash log requested, that report is not important anymore. It is formally valid (it is not a cat picture) but it is not the one we need now.

> > UserScripts is still considered an experimental feature, see #792
> 
> In other words, you don't care?

Again, toxic behaviour. Please stop. Experimental means experimental, go find the definition in a dictionary.

> In regards to SAF functionality, I humbly plead a request to completely avoid such functionality and simply use a built in file picker.

You should open a discussion for that; this is a bug report about a crash, I understand it's related but it's not the right place to discuss it.

> If you truly do care enough to fix this and still wish to see the userscript logs, please confirm and I will get them from adb. I just don't want to waste anyone's time if nobody thinks it is actually important (a sentiment I have felt up until now).

If you truly do care enough to see this fixed then stop the drama and keep the discussion exclusively about the technical aspects; do not talk about sentiments, do not talk about feelings, do not talk about what you assume. Talk about how to do X, how to do Y etc.
Please make sure that your next comment is a technical question or answer or I will moderate this issue.

**Comment by csagan5** [comment]
> > Again, you are not supposed to suppose anything: read comments, do what is asked if you want to contribute, otherwise don't do it but don't complain that things are not as you expect. You were told in #1928 what to do, you could/would not do it and you did not ask for help but instead complained, and you still are. This is toxic behaviour so please stop.
> 
> You're the one with the "Contributor" badge. You're supposed to be contributing, not badgering and hassling people trying to report bugs to improve the software. Maybe you don't care about this app, but some other people might, and you are directly sabotaging legitimate feedback with your illegitimate authority, noob. You are unable to read and comprehend plain English. You repeat the same nonsense over and over. Telling somebody to do something after they have done it? You aren't fooling anybody, you're a fool.
> 
> > That is because that report was created before the tests that were asked of you, not after. Given the new tests/crash log requested, that report is not important anymore. It is formally valid (it is not a cat picture) but it is not the one we need now.
> 
> What are you blabbering on about? You are obviously not trying to improve Bromite. You can't even follow short and simple timelines let alone comprehend a technical issue. What you should really be doing is moderating your own stroking of ego (purr).
> 
> > Again, toxic behaviour. Please stop. Experimental means experimental, go find the definition in a dictionary.
> 
> You're toxic. You sit here policing this project like you know something when you are really just a loser with a God complex looking to boss people around. You think you are insulting people by calling them toxic, yet its your disgusting personality that's visible when you post. You are talk sick. clap
> 
> > You should open a discussion for that; this is a bug report about a crash, I understand it's related but it's not the right place to discuss it.
> 
> You should find a job. Preferably in politics where disgusting personalities like you thrive on power lust, brown nosing, secrets, and flattery. That would be the right place for you.
> 
> > If you truly do care enough to see this fixed then stop the drama and keep the discussion exclusively about the technical aspects; do not talk about sentiments, do not talk about feelings, do not talk about what you assume. Talk about how to do X, how to do Y etc.
> 
> Why would I help fix any trash program that _you_ are representing? Bromite is utter diarrhea now thanks to you. It's a complete joke. The only way they can get support is by using bros who might... If you are the face of this software, the only thing that can help is a guillotine. You are the most pathetic hypocrite I have ever seen, hiding behind your computer screen, acting all hard and mean, trying to increase your peen. "Do not talk about sentiments, do not talk about feee.... YOU'RE TOXIC". HAHA rofl rofl. Reading your writing is like watching a mentally handicapped child play with firearms. muscle fire
> 
> > Please make sure that your next comment is a technical question or answer or I will moderate this issue.
> 
> Well I wouldn't you to unleash all your powerful _moderation_. You're far too much of an extremist to moderate, so I will be forced to submit my technical answer. 1 + 1 = 1;

I will leave your message here but I do not need to answer as there is no technical question here.

**Comment by uazo** [comment]
> @uazo is this crash also invalid? Perhaps the error "Cannot open script source." could tell a bit more about the reason?

it is not a crash but a log, it should be checked for more information about the error.

> @uazo does SAF correspond to a dependency on the Android download manager?

I don't even know what the **Android** Download Manager is.
SAF is an android framework which is certainly used by **a** download manager, but the chromium code does not use external references for download management, so much so that it creates a saf provider. do you mean that?

> I have a rooted phone and have disabled the Download manager
> If you weren't aware, that thing allows any app on the phone to access the internet at any time which bypasses firewall rules.

this is fundamental information, give us references to what you did and the source of that statement.
that is, assuming that we are the download manager, do we allow access to applications a priori?
