### ISSUE TITLE
Bromite crashes when GMS is unable to download fonts

### ISSUE THREAD

**Issue by dvalter** [bromite/bromite#2156]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

102.0.5005.96

### Device architecture

arm64

### Android version

12.1

### Device model

Sony H4113 (pioneer)

### Changed flags

no flags changed

### Is this bug about the SystemWebView?

No

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

Yes. Backtrace
```
06-25 15:37:24.238  7882  7927 I FontLog : Received query name=Google Sans&weight=700&besteffort=false, URI content://com.google.android.gms.fonts [CONTEXT service_id=132 ]
06-25 15:37:24.239 12616 12616 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
06-25 15:37:24.240  7882  7927 I FontLog : Query [name=Google Sans&weight=700&besteffort=false] resolved to {Google Sans, wdth 100.0, wght 700, ital 0.0, bestEffort false} [CONTEXT service_id=132 ]
06-25 15:37:24.239     0     0 I binder  : 12616:12616 ioctl 40046210 7fddc97044 returned -22
06-25 15:37:24.244  7882  7927 I FontLog : Font PFD returned from cache for {Google Sans, wdth 100.0, wght 700, ital 0.0, bestEffort false} [CONTEXT service_id=132 ]
06-25 15:37:24.245  7882  7927 I FontLog : Fetch {Google Sans, wdth 100.0, wght 700, ital 0.0, bestEffort false} end status Status{statusCode=SUCCESS, resolution=null} [CONTEXT service_id=132 ]
06-25 15:37:24.250  7882  8292 I FontLog : Pulling font file for id = 3, cache size = 3 [CONTEXT service_id=132 ]
06-25 15:37:24.255  6424  6565 I Icing   : Indexing com.google.android.gms-apps from com.google.android.gms
06-25 15:37:24.261  7882  7927 I FontLog : Received query name=Noto Color Emoji Compat&weight=400&besteffort=false, URI content://com.google.android.gms.fonts [CONTEXT service_id=132 ]
06-25 15:37:24.263  7882  7927 I FontLog : Query [name=Noto Color Emoji Compat&weight=400&besteffort=false] resolved to {Noto Color Emoji Compat, wdth 100.0, wght 400, ital 0.0, bestEffort false} [CONTEXT service_id=132 ]
06-25 15:37:24.280   722 12640 D resolv  : GetAddrInfoHandler::run: {0 786432 0 983040 1010091 0}
06-25 15:37:24.280   722 12640 D resolv  : resolv_getaddrinfo: explore_fqdn(): ai_family=0 ai_socktype=1 ai_protocol=6
06-25 15:37:24.283  7882  8108 W FontLog : Connection failure for https://fonts.gstatic.com/s/a/directory022.pb [CONTEXT service_id=132 ]
06-25 15:37:24.299  7882  8108 E AndroidRuntime: FATAL EXCEPTION: highpool[6]
06-25 15:37:24.299  7882  8108 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 7882
06-25 15:37:24.299  7882  8108 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'aehc aehd.a' on a null object reference
06-25 15:37:24.299  7882  8108 E AndroidRuntime:        at aegu.e(:com.google.android.gms@214815044@21.48.15 (190400-414534850):3)
06-25 15:37:24.299  7882  8108 E AndroidRuntime:        at aegt.run(:com.google.android.gms@214815044@21.48.15 (190400-414534850):0)
06-25 15:37:24.299  7882  8108 E AndroidRuntime:        at voi.c(:com.google.android.gms@214815044@21.48.15 (190400-414534850):6)
06-25 15:37:24.299  7882  8108 E AndroidRuntime:        at voi.run(:com.google.android.gms@214815044@21.48.15 (190400-414534850):7)
06-25 15:37:24.299  7882  8108 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-25 15:37:24.299  7882  8108 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-25 15:37:24.299  7882  8108 E AndroidRuntime:        at vuh.run(:com.google.android.gms@214815044@21.48.15 (190400-414534850):0)
06-25 15:37:24.299  7882  8108 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:920)
06-25 15:37:24.302  7882  8108 I GCore-Chimera-Crash: ChkKCWNvbnRhaW5lchCvqbdmGEAggOuPwsI-IAA=
06-25 15:37:24.302  7882  8108 I GCore-Chimera-Crash: GCore-Chimera-Crash
06-25 15:37:24.305  7882  8108 I DeviceDrDatabaseHelper: Cleaning stale data from database!
06-25 15:37:24.356  7882  8108 W DeviceDoctorHandler: Crash Hash: 27b9654bee6d927f89bb99eff635d5db52b5ef8d
06-25 15:37:24.360  7882  8108 W DeviceDoctorHandler: Shushing crash.
06-25 15:37:24.360  7882  8108 E DeviceDoctorHandler: FATAL EXCEPTION: highpool[6]
06-25 15:37:24.360  7882  8108 E DeviceDoctorHandler: Process: com.google.android.gms.persistent, PID: 7882
06-25 15:37:24.360  7882  8108 E DeviceDoctorHandler: java.lang.NullPointerException: Attempt to read from field 'aehc aehd.a' on a null object reference
06-25 15:37:24.360  7882  8108 E DeviceDoctorHandler:   at aegu.e(:com.google.android.gms@214815044@21.48.15 (190400-414534850):3)
06-25 15:37:24.360  7882  8108 E DeviceDoctorHandler:   at aegt.run(:com.google.android.gms@214815044@21.48.15 (190400-414534850):0)
06-25 15:37:24.360  7882  8108 E DeviceDoctorHandler:   at voi.c(:com.google.android.gms@214815044@21.48.15 (190400-414534850):6)
06-25 15:37:24.360  7882  8108 E DeviceDoctorHandler:   at voi.run(:com.google.android.gms@214815044@21.48.15 (190400-414534850):7)
06-25 15:37:24.360  7882  8108 E DeviceDoctorHandler:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-25 15:37:24.360  7882  8108 E DeviceDoctorHandler:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-25 15:37:24.360  7882  8108 E DeviceDoctorHandler:   at vuh.run(:com.google.android.gms@214815044@21.48.15 (190400-414534850):0)
06-25 15:37:24.360  7882  8108 E DeviceDoctorHandler:   at java.lang.Thread.run(Thread.java:920)
06-25 15:37:24.360  7882  8108 E DeviceDoctorHandler: 
06-25 15:37:24.366  1673  1835 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
06-25 15:37:24.366 12473 12473 I cr_OfflineIndicator: onConnectionTypeChanged 6
06-25 15:37:24.367 12473 12473 I cr_OfflineIndicator: setConnectionState connectionState=1
06-25 15:37:24.367 12473 12473 I cr_OfflineDetector: Running updateState mConnectivityDetectorInitialized: true, mTimeWhenLastForegrounded: 295071, getElapsedTime: 295071, mTimeWhenLastOfflineNotificationReceived: 295071, mTimeWhenLastOnline: 0, mApplicationState: 1, mIsOfflineLastReportedByConnectivityDetector: true, mIsEffectivelyOffline: false
06-25 15:37:24.367 12473 12473 I cr_OfflineDetector: updateState(): timeSinceLastForeground: 0, timeSinceOfflineNotificationReceived: 0, timeSinceLastOnline: 295071, timeNeededForForeground: 2000, timeNeededForOffline: 2000
06-25 15:37:24.370  7882  8108 I Process : Sending signal. PID: 7882 SIG: 9
06-25 15:37:24.372  1673  1806 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-25 15:37:24.372  1673  1806 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
06-25 15:37:24.372  1673  1806 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-25 15:37:24.372  1673  1806 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
06-25 15:37:24.403 12473 12528 I ActivityThread: Removing dead content provider:android.content.ContentProviderProxy@7df8d51
06-25 15:37:24.404  1673  2228 I ActivityManager: Process com.google.android.gms.persistent (pid 7882) has died: fg  BTOP
06-25 15:37:24.405 12473 12473 E ResourcesCompat: Failed to find font-family tag
06-25 15:37:24.402     0     0 I binder  : release 7882:7927 transaction 502117 in, still active
06-25 15:37:24.402     0     0 I binder  : send failed reply for transaction 502117 to 12473:12528
06-25 15:37:24.404     0     0 I binder  : 1673:2586 transaction failed 29189/-22, size 0-0 line 3019
06-25 15:37:24.405     0     0 I binder  : undelivered transaction 502335, process died.
06-25 15:37:24.405  1673  1808 I libprocessgroup: Successfully killed process cgroup uid 1010091 pid 7882 in 0ms
06-25 15:37:24.407  1673  2228 I ActivityManager: Killing 12473:org.bromite.bromite/u10a142 (adj 0): depends on provider com.google.android.gms/.fonts.provider.FontsProvider in dying proc com.google.android.gms.persistent (adj -10000)
06-25 15:37:24.407  1673  2108 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:1010091/7882, android.os.BinderProxy@1ee147)
06-25 15:37:24.408  1673 12663 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:1010091/7882, android.os.BinderProxy@9b3bd74)
06-25 15:37:24.409  1673  1883 D ConnectivityService: releasing NetworkRequest [ REQUEST id=103, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 1010091 RequestorUid: 1010091 RequestorPkg: com.google.android.gms] ] (release request)
06-25 15:37:24.409  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/com.google.android.location.internal.server.GoogleLocationService in 1000ms for start-requested
06-25 15:37:24.411  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.presencemanager.service.PresenceManagerPresenceReportService in 10999ms for start-requested
06-25 15:37:24.411  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.deviceconnection.service.DeviceConnectionWatcherService in 20998ms for start-requested
06-25 15:37:24.411  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.nearby.sharing.ReceiveSurfaceService in 30998ms for start-requested
06-25 15:37:24.411  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.common.stats.GmsCoreStatsService in 40998ms for start-requested
06-25 15:37:24.411  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.chimera.PersistentDirectBootAwareApiService in 50998ms for connection
06-25 15:37:24.411  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.nearby.exposurenotification.service.ExposureMatchingService in 60998ms for start-requested
06-25 15:37:24.412  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/com.google.android.contextmanager.service.ContextManagerService in 70998ms for start-requested
06-25 15:37:24.412  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.thunderbird.EmergencyPersistentService in 80998ms for start-requested
06-25 15:37:24.412  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.location.persistent.LocationPersistentService in 90998ms for start-requested
06-25 15:37:24.412  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.chimera.PersistentIntentOperationService in 100997ms for start-requested
06-25 15:37:24.412  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.clearcut.debug.ClearcutDebugDumpService in 110997ms for start-requested
06-25 15:37:24.412  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/com.google.android.location.internal.GoogleLocationManagerService in 120997ms for start-requested
06-25 15:37:24.412  1673  2228 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.auth.setup.devicesignals.LockScreenService in 130997ms for start-requested
06-25 15:37:24.424   723   723 I Zygote  : Process 7882 exited due to signal 9 (Killed)

```

### Describe the bug

Crash a few seconds after app launch when GMS is installed but unable to go online (i.e. firewalled) After about ten subsequent crashes it stops happening before device reboot

### Steps to reproduce the bug

1. Go offline
2. Create a work profile (i.e. with Insular; full factory reset or new user should work as well)
3. Install Bromite/Chromium
4. Launch the app

### Expected behavior

No crashes

**Comment by csagan5** [comment]
Fixed in `103.0.5060.121`.

@dvalter if issue is not fixed please report back.
