### ISSUE TITLE
Crash on Android 4.2.2

### ISSUE THREAD

**Issue by qtwu** [bromite/bromite#310]
**Bromite version**

Version: 75.0.3770.50
Arch: arm
Android version: Android 4.2.2

**Is the bug reproducible with latest version?**
Yes.

**Can the bug be reproduced with corresponding [Chromium]**
Could not tested.

**Is the bug a crash?**
Yes.
------------------------Crash log------------------------
Process: org.bromite.bromite
Flags: 0xc83e44
Package: org.bromite.bromite v1558399690 (75.0.3770.50)
Build: Onyx/C67ML/C67ML:4.2.2/JDQ_1704260959/100:user/release-keys

java.lang.NoClassDefFoundError: java.util.Objects
	at _h.a(PG:2)
	at UKb.a(PG:2)
	at HKb.d(PG:3)
	at EKb.e(PG:1)
	at Zga.b(PG:6)
	at Zga.a(PG:6)
	at HKb.<init>(PG:19)
	at HKb.a(PG:9)
	at hTa.c(PG:10)
	at hTa.h(PG:5)
	at BSa.a(PG:14)
	at iSa.onCreate(PG:33)
	at android.app.Activity.performCreate(Activity.java:5104)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
	at android.app.ActivityThread.access$600(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
------------------------Crash log------------------------

**Describe the bug**
Bromite crash when launching.

**Comment by csagan5** [comment]
I have verified this problem however the solution will be to move the minimum SDK version from 17 to 19 (Android 4.4.+) as upstream Chromium does already.

You can expect next version to require Android 4.4.+; this issue will be closed with such release.

**Comment by qtwu** [comment]
> I have verified this problem however the solution will be to move the minimum SDK version from 17 to 19 (Android 4.4.+) as upstream Chromium does already.
> 
> You can expect next version to require Android 4.4.+; this issue will be closed with such release.

Bromite 75.0.3770.53 still crash on my device. However, I have to admit that Android 4.2.2 is out of date even if for E-ink devices. I understand this. Thanks!

**Comment by csagan5** [comment]
Fixed in `75.0.3770.70`.

**Comment by DI555** [comment]
My 5 cent qestion, were any tryings to move and use the minimum SDK version to 18 (Android 4.3.+)  ?
Was it workable ?

**Comment by csagan5** [comment]
@DI555 yes, there were. It was not easy to maintain and it would cause crashes.
