### ISSUE TITLE
Crash when trying to change homepage

### ISSUE THREAD

**Issue by kowith337** [bromite/bromite#394]
**Bromite version**

> Version: `78.0.3904.63`
> Arch: `arm64 (ChromeModernPublic)`
> Android version: `9.0`
> Device model: `XT1970-3 (kane)`

**Is this bug about the SystemWebView?**
> No, because I cannot install.

**Is the bug reproducible with latest version?**
> Yes and it's happen in the current version.

**Can the bug be reproduced with corresponding Chromium version?**
> No

**Is the bug a crash?**
> Yes

**Describe the bug**

Write here a clear and concise description of the bug.

**To Reproduce**

1. Open Bromite
2. Click on `Menu button` \> `Settings`
3. In settings page, tap to `Homepage`
4. App crashed

**Expected behavior**
> You can access homepage settings, in order to change.

**Screenshots**
![image](https://user-images.githubusercontent.com/16535467/67292353-19ef3d80-f50d-11e9-8e51-0db5214ff131.png)

**Logs**
```10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: FATAL EXCEPTION: main
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: Process: org.bromite.bromite, PID: 25461
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: android.view.InflateException: Binary XML file line #14: Error inflating class (not found)org.chromium.chrome.browser.preferences.ChromeSwitchPreferenceCompat
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at Sc.a(PG:49)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at Sc.a(PG:75)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at Sc.a(PG:8)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at Lc.g(PG:8)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at bV0.a(PG:2)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at org.chromium.chrome.browser.preferences.HomepagePreferences.a(PG:3)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at Lc.b(PG:10)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at N2.a(PG:234)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at Z2.a(PG:238)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at Z2.a(PG:11)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at N2.a(PG:617)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at N2.c(PG:48)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at N2.o(PG:4)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at N2.b(PG:30)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at N2.g(PG:22)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at r2.onStart(PG:6)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at N8.onStart(PG:1)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1413)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7169)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3146)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:220)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6929)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.preferences.ChromeSwitchPreferenceCompat" on path: DexPathList[[zip file "/data/app/org.bromite.bromite-FX_qujiTy8Sjft6C5YhilQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.bromite.bromite-FX_qujiTy8Sjft6C5YhilQ==/lib/arm64, /data/app/org.bromite.bromite-FX_qujiTy8Sjft6C5YhilQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at Sc.a(PG:29)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	at Sc.a(PG:43)
10-22 13:34:12.398 1010343 25461 25461 E AndroidRuntime: 	... 30 more```

**Comment by OffifialMITX** [comment]
Confirm same issue on same version, Android 7.1.1 XT1771

**Comment by HyknuF** [comment]
Same issue on Android 9, Oneplus A6003 (LOS 16)

**Comment by csagan5** [comment]
Fixed in `78.0.3904.72`

**Comment by OffifialMITX** [comment]
Working confirmed.
