### ISSUE TITLE
Build for x86 64-bit

### ISSUE THREAD

**Issue by mwriter** [bromite/bromite#55]
Please make builds for x86 64-bit.
```
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.android.webview-1/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.browser/com.android.browser.BrowserActivity}: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5415)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
Caused by: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:169)
    at android.webkit.CookieManager.getInstance(CookieManager.java:39)
    at com.android.browser.BrowserSettings.syncSharedSettings(BrowserSettings.java:312)
    at com.android.browser.BrowserSettings.setController(BrowserSettings.java:148)
    at com.android.browser.Controller.<init>(Controller.java:235)
    at com.android.browser.BrowserActivity.createController(BrowserActivity.java:84)
    at com.android.browser.BrowserActivity.onCreate(BrowserActivity.java:73)
    at android.app.Activity.performCreate(Activity.java:6262)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    ... 10 more
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:163)
    ... 19 more
Caused by: java.lang.RuntimeException: Cannot load WebView
    at org.chromium.android_webview.AwBrowserProcess.loadLibrary(AwBrowserProcess.java:82)
    at com.android.webview.chromium.WebViewChromiumFactoryProvider.initialize(WebViewChromiumFactoryProvider.java:216)
    at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:170)
    ... 21 more
Caused by: org.chromium.base.library_loader.ProcessInitException
    at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:445)
    at org.chromium.base.library_loader.LibraryLoader.loadNowOverrideApplicationContext(LibraryLoader.java:226)
    at org.chromium.android_webview.AwBrowserProcess.loadLibrary(AwBrowserProcess.java:1210)
    ... 23 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.android.webview-1/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit
    at java.lang.Runtime.loadLibrary(Runtime.java:372)
    at java.lang.System.loadLibrary(System.java:1076)
    at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:420)
    ... 25 more
```

**Comment by csagan5** [comment]
@mwriter can you report here the navigator platform of your device? You can see it here https://www.bromite.org/detect under General.

**Comment by mwriter** [comment]
Navigator platform is: Linux i686

**Comment by csagan5** [comment]
@mwriter what is your Android version and which Bromite .apk did you install?

**Comment by csagan5** [comment]
Related issue: #48

**Comment by mwriter** [comment]
Android 6.0.1 x86 64-bit
x86_SystemWebView.apk

**Comment by csagan5** [comment]
@mwriter from the dump you posted, you installed the ARM version, not x86.

Try installing the x86 SystemWebView. I am not adding new architecture for now as the build server resources are limited, sorry.

**Comment by mwriter** [comment]
I tried everything

Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.android.webview-1/lib/x86/libwebviewchromium.so" is 32-bit instead of 64-bit

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.browser/com.android.browser.BrowserActivity}: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5415)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
Caused by: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:169)
	at android.webkit.CookieManager.getInstance(CookieManager.java:39)
	at com.android.browser.BrowserSettings.syncSharedSettings(BrowserSettings.java:312)
	at com.android.browser.BrowserSettings.setController(BrowserSettings.java:148)
	at com.android.browser.Controller.<init>(Controller.java:235)
	at com.android.browser.BrowserActivity.createController(BrowserActivity.java:84)
	at com.android.browser.BrowserActivity.onCreate(BrowserActivity.java:73)
	at android.app.Activity.performCreate(Activity.java:6262)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:163)
	... 19 more
Caused by: java.lang.RuntimeException: Cannot load WebView
	at org.chromium.android_webview.AwBrowserProcess.loadLibrary(AwBrowserProcess.java:82)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.initialize(WebViewChromiumFactoryProvider.java:216)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:170)
	... 21 more
Caused by: org.chromium.base.library_loader.ProcessInitException
	at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:445)
	at org.chromium.base.library_loader.LibraryLoader.loadNowOverrideApplicationContext(LibraryLoader.java:226)
	at org.chromium.android_webview.AwBrowserProcess.loadLibrary(AwBrowserProcess.java:1210)
	... 23 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.android.webview-1/lib/x86/libwebviewchromium.so" is 32-bit instead of 64-bit
	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	at java.lang.System.loadLibrary(System.java:1076)
	at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:420)
	... 25 more

**Comment by mwriter** [comment]
Why did you close this issue?
Maybe someone else can help me.

**Comment by csagan5** [comment]
@mwriter these Github issues are for actionable items. For general discussions I suggest [the official thread on XDA Developers](https://forum.xda-developers.com/android/apps-games/app-bromite-chromium-plus-adblocking-t3687258).

I am not building for x86 64bit, sorry. Maybe in future.
