### ISSUE TITLE
App crashes when clicking on Print page of share menu in browser

### ISSUE THREAD

**Issue by possumhub** [bromite/bromite#713]
### Bromite version

Version: `85.0.4183.82`
Arch: `arm64`
Android version: 8.1
Device model: Redmi 4a

### Is this bug about the SystemWebView?
No

### Is the bug reproducible with latest version?
Yes 

### Can the bug be reproduced with corresponding Chromium version?
No 

### Describe the bug
Whenever I want to print a webpage and click on Print option from share menu, the browser crashes outright.

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to 'any webpage'
2. Click on 'click on Print option from share menu'
3. See error

**Comment by csagan5** [comment]
I cannot reproduce this issue; please report the crash log with `adb logcat` or similar.

**Comment by basimaslamts** [comment]
I could produce this issue.
 Latest version bromite
Redmi 7 Onclite

**Comment by csagan5** [comment]
@basimaslamts please report the crash log then, otherwise it cannot be tracked down.

**Comment by possumhub** [comment]
> I cannot reproduce this issue; please report the crash log with `adb logcat` or similar.

FATAL EXCEPTION: main
Process: org.bromite.bromite, PID: 4330
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.bromite.bromite/org.chromium.chrome.browser.printing.PrintShareActivity}: java.lang.IllegalStateException: Can print only from an activity
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2811)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6578)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:460)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Caused by: java.lang.IllegalStateException: Can print only from an activity

**Comment by csagan5** [comment]
Does this happen with Bromite with default settings or you have changed some settings first?

**Comment by possumhub** [comment]
> Does this happen with Bromite with default settings or you have changed some settings first?

Yes, it's after I've change some settings. I didn't try before changing settings. I'll test with fresh install and tell you.

**Comment by possumhub** [comment]
I'm sorry for commenting so late. I had some personal issues.

**Comment by csagan5** [comment]
Sure, no problem; if you can still find which settings were changed, it might be beneficial to address the bug here in Bromite or Chromium.
