### ISSUE TITLE
Does not play video link from google drive

### ISSUE THREAD

**Issue by keywan2020** [bromite/bromite#889]
### Bromite version

Version: `Bromite v87.0.4280.131`
Arch:  `arm64` 
Android version: 9
Device model: Blackview A60 Pro

### Is this bug about the SystemWebView?
 No

### Is the bug reproducible with latest version?

Yes

### Can the bug be reproduced with corresponding Chromium version?

yes

### Is the bug a crash?

no crash

### Describe the bug

Does not play video
CC license video from big buck bunny
https://drive.google.com/file/d/1LydrTy4V63DVaeEG0s9NuRBppTwgtrj4/view

### Steps to reproduce the bug

Steps to reproduce the bug:
1. Go to https://drive.google.com/file/d/1LydrTy4V63DVaeEG0s9NuRBppTwgtrj4/view
2. Click on play button (in the video)
3. Nothing happens
(Note this link video works OK with Firefox Klar from fdroid.)

### Expected behavior

Play the video

### Screenshots

```

s15/u0a78i290 (adj 904): isolated not needed
01-23 12:28:59.854  1049  1135 W libprocessgroup: kill(-12811, 9) failed: No such process
01-23 12:28:59.854  1049  1135 I libprocessgroup: Successfully killed process cgroup uid 99290 pid 12811 in 1ms
01-23 12:28:59.871 12818 12818 E libc    : Access denied finding property "persist.vendor.sys.activitylog"
01-23 12:28:59.869 12818 12818 W re-initialized>: type=1400 audit(0.0:2332): avc: denied { read } for name="u:object_r:mtk_amslog_prop:s0" dev="tmpfs" ino=12857 scontext=u:r:isolated_app:s0:c35,c257,c512,c768 tcontext=u:object_r:mtk_amslog_prop:s0 tclass=file permissive=0
01-23 12:28:59.891   386   877 D APM_AudioPolicyManager: AudioPolicyManager:setRecordSilenced(uid:99291, silenced:0)
01-23 12:28:59.892   386   877 D AudioFlinger: AudioFlinger::setRecordSilenced(uid:99291, silenced:0)
01-23 12:29:00.001  1049  1196 E MtkDataShapingUtils: Exception openLteGateByDataShaping  in java.lang.NullPointerException: null receiver
01-23 12:29:00.001  1049  1196 W System.err: java.lang.NullPointerException: null receiver
01-23 12:29:00.001  1049  1196 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
01-23 12:29:00.001  1049  1196 W System.err: 	at com.mediatek.server.MtkDataShaping.openLteGateByDataShaping(MtkDataShaping.java:36)
01-23 12:29:00.002  1049  1196 W System.err: 	at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:3607)
01-23 12:29:00.002  1049  1196 W System.err: 	at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:3785)
01-23 12:29:00.033   393   424 I BufferQueueProducer: [StatusBar#0](this:0x724211a800,id:3,api:1,p:1262,c:393) queueBuffer: fps=0.66 dur=30167.47 max=29349.14 min=5.04
01-23 12:29:00.042   393  1210 I BufferQueueProducer: [org.bromite.bromite/com.google.android.apps.chrome.Main#0](this:0x7246ca1000,id:1063,api:1,p:24347,c:393) queueBuffer: fps=16.62 dur=1444.13 max=752.75 min=8.32
01-23 12:29:00.090 24347 24347 I cr_tabmodel: Appending tabs being restored to metadata lists, 0, startingNormalCount: 2, startingIncognitoCount: 0
01-23 12:29:00.090 24347 24347 I cr_tabmodel: Serializing tab lists; counts: 2, 0
01-23 12:29:00.256  1049  1287 D AES     : AEEIOCTL_GET/SET_SF_STATE IOCTL,cmd= 1074294797, lParam=0. 
01-23 12:29:00.256  1049  1287 D AES     : AEEIOCTL_RT_MON_Kick IOCTL,cmd= 2147774474, lParam=300. 
01-23 12:29:00.357 12818 12818 W boxed_process15: type=1400 audit(0.0:2333): avc: denied { getattr } for path="/data/data/org.bromite.bromite" dev="dm-1" ino=57492 scontext=u:r:isolated_app:s0:c35,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c78,c256,c512,c768 tclass=dir permissive=0
01-23 12:29:00.420 24347 10074 D OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
01-23 12:29:00.420 24347 10074 D OpenSSLLib: OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
01-23 12:29:00.429 12818 12818 I cr_ChildProcessService: Creating new ChildProcessService pid=12818
01-23 12:29:00.445 12818 12837 I cr_Linker: Using linker: org.chromium.base.library_loader.LegacyLinker
01-23 12:29:00.452 12818 12840 I cr_LibraryLoader:  Loading chrome from within /data/app/org.bromite.bromite-Zf5OSn3MSIMwN4cJUqvB0A==/base.apk
01-23 12:29:00.509   393  1210 I SurfaceFlinger: [SF client] Remove(0x72420a6540) for (-950803560:)
01-23 12:29:00.509   393   424 I SurfaceFlinger: [SF client] Remove(0x723e113c80) for (-950803560:)
01-23 12:29:00.509   393   424 I SurfaceFlinger: [SF client] Remove(0x7246c2f6c0) for (-950803560:)
01-23 12:29:00.509   393  1210 I SurfaceFlinger: [SF client] Remove(0x7246c2f600) for (539828324:)
01-23 12:29:00.509   393   424 I SurfaceFlinger: [SF client] Remove(0x723e1144c0) for (-950803560:)
01-23 12:29:00.509   393  1209 I SurfaceFlinger: [SF client] Remove(0x723e113bc0) for (1080:)
01-23 12:29:00.589 12818 12840 I cr_LibraryLoader: Loaded native library version number "86.0.4240.73"
01-23 12:29:00.590 12818 12840 I cr_CachingUmaRecorder: Flushed 1 samples from 1 histograms.
01-23 12:29:00.655   393   616 I BufferQueueProducer: [SurfaceView - org.bromite.bromite/com.google.android.apps.chrome.Main#0](this:0x72421bd800,id:1064,api:1,p:24435,c:393) queueBuffer: fps=45.64 dur=1007.88 max=157.91 min=5.84
01-23 12:29:00.665   393   393 I SurfaceFlinger: [Built-in Screen (type:0)] fps:44.899868,dur:1002.23,max:145.10,min:16.36
01-23 12:29:00.808  1049  1134 I ActivityManager: Start proc 12850:org.bromite.bromite:sandboxed_process16/u0i292 for service org.bromite.bromite/org.chromium.content.app.SandboxedProcessService16
01-23 12:29:00.823 12850 12850 E boxed_process1: Not starting debugger since process cannot load the jdwp agent.
01-23 12:29:00.826  1049  1134 I ActivityManager: Start proc 12856:org.bromite.bromite:sandboxed_process16/u0i293 for service org.bromite.bromite/org.chromium.content.app.SandboxedProcessService16
01-23 12:29:00.837 12850 12850 W re-initialized>: type=1400 audit(0.0:2334): avc: denied { read } for name="u:object_r:mtk_amslog_prop:s0" dev="tmpfs" ino=12857 scontext=u:r:isolated_app:s0:c36,c257,c512,c768 tcontext=u:object_r:mtk_amslog_prop:s0 tclass=file permissive=0
01-23 12:29:00.838 12850 12850 E libc    : Access denied finding property "persist.vendor.sys.activitylog"
01-23 12:29:00.841 12856 12856 E boxed_process1: Not starting debugger since process cannot load the jdwp agent.
01-23 12:29:00.845  1049  7756 I ActivityManager: Killing 12850:org.bromite.bromite:sandboxed_process16/u0a78i292 (adj 904): isolated not needed
01-23 12:29:00.846  1049  1135 W libprocessgroup: kill(-12850, 9) failed: No such process
01-23 12:29:00.846  1049  1135 I libprocessgroup: Successfully killed process cgroup uid 99292 pid 12850 in 0ms
01-23 12:29:00.852 12856 12856 E libc    : Access denied finding property "persist.vendor.sys.activitylog"
01-23 12:29:00.849 12856 12856 W re-initialized>: type=1400 audit(0.0:2335): avc: denied { read } for name="u:object_r:mtk_amslog_prop:s0" dev="tmpfs" ino=12857 scontext=u:r:isolated_app:s0:c37,c257,c512,c768 tcontext=u:object_r:mtk_amslog_prop:s0 tclass=file permissive=0
01-23 12:29:00.859   386  5480 D APM_AudioPolicyManager: AudioPolicyManager:setRecordSilenced(uid:99293, silenced:0)
01-23 12:29:00.859   386  5480 D AudioFlinger: AudioFlinger::setRecordSilenced(uid:99293, silenced:0)
01-23 12:29:00.923  1049  1219 E WifiVendorHal: getWifiLinkLayerStats(l.937) failed {.code = ERROR_NOT_SUPPORTED, .description = }
01-23 12:29:00.971   669   905 I VT      : [VTS] gVTSClient == NULL
01-23 12:29:01.265 12856 12856 W boxed_process16: type=1400 audit(0.0:2336): avc: denied { getattr } for path="/data/data/org.bromite.bromite" dev="dm-1" ino=57492 scontext=u:r:isolated_app:s0:c37,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c78,c256,c512,c768 tclass=dir permissive=0
01-23 12:29:01.269  1707  1707 I ADB_SERVICES: fdevent_loop length=1
01-23 12:29:01.319 12856 12856 I cr_ChildProcessService: Creating new ChildProcessService pid=12856
01-23 12:29:01.330 12856 12874 I cr_Linker: Using linker: org.chromium.base.library_loader.LegacyLinker
01-23 12:29:01.337 12856 12877 I cr_LibraryLoader:  Loading chrome from within /data/app/org.bromite.bromite-Zf5OSn3MSIMwN4cJUqvB0A==/base.apk
01-23 12:29:01.445 12856 12877 I cr_LibraryLoader: Loaded native library version number "86.0.4240.73"
01-23 12:29:01.446 12856 12877 I cr_CachingUmaRecorder: Flushed 1 samples from 1 histograms.
01-23 12:29:01.746 24347 24347 I cr_tabmodel: Appending tabs being restored to metadata lists, 0, startingNormalCount: 2, startingIncognitoCount: 0
01-23 12:29:01.746 24347 24347 I cr_tabmodel: Serializing tab lists; counts: 2, 0
01-23 12:29:03.019   393  1209 I BufferQueueProducer: [SurfaceView - org.bromite.bromite/com.google.android.apps.chrome.Main#0](this:0x72421bd800,id:1064,api:1,p:24435,c:393) queueBuffer: fps=2.54 dur=2363.38 max=2202.58 min=15.09
01-23 12:29:03.032   393   393 I SurfaceFlinger: [Built-in Screen (type:0)] fps:2.957137,dur:2367.15,max:2195.91,min:17.63
01-23 12:29:03.931  1049  1219 E WifiVendorHal: getWifiLinkLayerStats(l.937) failed {.code = ERROR_NOT_SUPPORTED, .description = }
01-23 12:29:05.394   699   728 D ApmSession: Connect
01-23 12:29:05.395   329   329 W hwservicemanager: getTransport: Cannot find entry vendor.mediatek.hardware.apmonitor@1.0::IAPMonitorService/default in either framework or device manifest.
01-23 12:29:05.396   699   728 D ApmSession: Connect: false
01-23 12:29:05.396   699   728 D ApmNative: apmIsKpiEnabled2: type = 54, ret = 0
01-23 12:29:05.625   694   694 I thermal_repeater: [recvMdThermalInfo] ret=37, strLen=127,  2, 32767, -127, 20821, 32767, -20554
01-23 12:29:05.972   669   905 I VT      : [VTS] gVTSClient == NULL
01-23 12:29:06.208  1049  1196 E MtkDataShapingUtils: Exception openLteGateByDataShaping  in java.lang.NullPointerException: null receiver
01-23 12:29:06.209  1049  1196 W System.err: java.lang.NullPointerException: null receiver
01-23 12:29:06.209  1049  1196 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
01-23 12:29:06.209  1049  1196 W System.err: 	at com.mediatek.server.MtkDataShaping.openLteGateByDataShaping(MtkDataShaping.java:36)
01-23 12:29:06.209  1049  1196 W System.err: 	at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:3607)
01-23 12:29:06.209  1049  1196 W System.err: 	at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:3785)
01-23 12:29:06.277  1049  1059 D MtkConnectivityService: requestNetwork for uid/pid:10095/26367 NetworkRequest [ TRACK_DEFAULT id=478, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10095] ]
01-23 12:29:06.282  1049  1219 D WIFI    : got request NetworkRequest [ TRACK_DEFAULT id=478, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10095] ] with score 60
01-23 12:29:06.282  1049  1219 D WIFI_UT : got request NetworkRequest [ TRACK_DEFAULT id=478, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10095] ] with score 60
01-23 12:29:06.282  1049  1241 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=478, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10095] ] with score 60
01-23 12:29:06.284  1372  1372 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=478, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10095] ] with score 60
01-23 12:29:06.941  1049  1219 E WifiVendorHal: getWifiLinkLayerStats(l.937) failed {.code = ERROR_NOT_SUPPORTED, .description = }

```

**Comment by csagan5** [comment]
Since the bug is reproducible with Chromium you have to report it on the Chromium issue tracker as explained through the issue template.
